name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: List build outputs
      if: success()
      run: |
        echo "Listing app/build/outputs"
        ls -R app/build/outputs || true

    - name: Show APK dir
      if: success()
      run: |
        echo "Listing app/build/outputs/apk/debug"
        ls -la app/build/outputs/apk/debug || true

    - name: Zip build outputs
      if: success()
      run: |
        mkdir -p release-artifacts
        if [ -d "app/build/outputs" ]; then
          zip -r release-artifacts/app-build-outputs.zip app/build/outputs || true
        else
          echo "No build outputs to zip"
        fi

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-build-artifacts
        path: |
          app/build/outputs/**/*.apk
          app/build/outputs/**
          release-artifacts/**
