name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: List build outputs
      if: success()
      run: |
        echo "Listing app/build/outputs"
        ls -R app/build/outputs || true

    - name: Show APK dir
      if: success()
      run: |
        echo "Listing app/build/outputs/apk/debug"
        ls -la app/build/outputs/apk/debug || true

    - name: Zip build outputs
      if: success()
      run: |
        mkdir -p release-artifacts
        if [ -d "app/build/outputs" ]; then
          zip -r release-artifacts/app-build-outputs.zip app/build/outputs || true
        else
          echo "No build outputs to zip"
        fi

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-build-artifacts
        path: |
          app/build/outputs/**/*.apk
          app/build/outputs/**
          release-artifacts/**

    - name: Create GitHub Release (draft)
      if: success()
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "ci-${{ github.run_id }}"
        release_name: "CI build ${{ github.run_number }}"
        body: |
          Automated build artifacts for run ${{ github.run_id }}.
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets to release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          release-artifacts/app-build-outputs.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
